### ISSUE TITLE
Travis funktioniert nicht

### ISSUE THREAD

**Issue by wiomoc** [hft-stuttgart-ipr/hft-asgmt-js-wiomoc#1]
> This is not an active repository

> You don't have sufficient rights to enable this repo on Travis.
> Please contact the admin to enable it or to receive admin rights yourself.

**Comment by maciossek** [comment]
![image](https://user-images.githubusercontent.com/1474347/55953987-c9458080-5c5d-11e9-91c4-b4caa8754781.png)

**Comment by maciossek** [comment]
Anmelden -> Aktivieren

**Comment by wiomoc** [comment]
Nachdem ich den PR gemergt habe, hats funktioniert
